### ISSUE TITLE
Not tracking Spring Onions

### ISSUE THREAD

**Issue by Palindine** [rei2hu/stardewvalley-esp#2]
Spring Onion is not tracked.
Adding it manually and re-loading the list removes it from the list

Screen 1: Pre-Harvest
![Stardew Valley 1 3 36 - running SMAPI 2 11 2 with 5 mods 2019-08-17 8_10_00 PM](https://user-images.githubusercontent.com/5550232/63218547-2af58a00-c12b-11e9-989f-a7555b893651.png)

Screen 2: Harvest
![Stardew Valley 1 3 36 - running SMAPI 2 11 2 with 5 mods 2019-08-17 8_10_05 PM](https://user-images.githubusercontent.com/5550232/63218548-2af58a00-c12b-11e9-8048-45091afbd19c.png)

Screen 3: Menu lacking Spring Onion
![Stardew Valley 1 3 36 - running SMAPI 2 11 2 with 5 mods 2019-08-17 8_10_17 PM](https://user-images.githubusercontent.com/5550232/63218549-2af58a00-c12b-11e9-83a9-8892a494afa2.png)

**Comment by rei2hu** [comment]
Looks like I might have missed every single possible crop that appears on tilled soil - thanks for bringing this up.

**Comment by rei2hu** [comment]
It should be fixed by ce790f7 which is included in the 1.1.2 release I just made.

**Comment by rei2hu** [comment]
Closing because fixed/no complaints.
